Internal PR: add BOB to L2Beat
bob-collective/l2beat pull request #1
Opened 2023-11-15 20:34 UTC by alexeiZamyatin

2023-11-27 09:19 UTC, nud3l requested changes

2023-11-27 09:19 UTC, nud3l commented on packages/config/src/layer2s/bob.ts
> +      'BOB ("Build on Bitcoin") is a layer 2 empowering everyone to build and innovate on Bitcoin. BOB is an OP Stack rollup that natively supports the Bitcoin stack, incl. Ordinals, Lightning and No
@alexeiZamyatin it sounds a bit like it all works due to zkVM but that isn't really the case.

2023-11-27 09:19 UTC, nud3l commented on packages/config/src/layer2s/bob.ts
> +      explorers: ['https://explorerl2-fluffy-bob-7mjgi9pmtg.t.conduit.xyz/'],
We should wait until we have the public Sepolia testnet launched in two weeks since this URL will be different.

2023-11-27 09:19 UTC, nud3l commented on packages/config/src/layer2s/bob.ts
> +    stage: 'NotApplicable',
Should be Stage 0 like OP Stack. But we can also add that later.

2023-11-28 00:12 UTC, alexeiZamyatin commented on packages/config/src/layer2s/bob.ts
> +    stage: 'NotApplicable',
I think stage is not applicabl until live

2023-11-28 00:12 UTC, alexeiZamyatin commented on packages/config/src/layer2s/bob.ts
> +      explorers: ['https://explorerl2-fluffy-bob-7mjgi9pmtg.t.conduit.xyz/'],
ACK

2023-11-28 00:16 UTC, alexeiZamyatin reviewed
Updated BOB description

2023-11-28 00:17 UTC, alexeiZamyatin commented on packages/config/src/layer2s/bob.ts
> +      'BOB ("Build on Bitcoin") is a layer 2 empowering everyone to build and innovate on Bitcoin. BOB is an OP Stack rollup that natively supports the Bitcoin stack, incl. Ordinals, Lightning and No
Updated

2023-11-28 01:35 UTC, nud3l approved these changes

2023-12-19 02:29 UTC, nud3l commented on packages/config/src/layer2s/bob.ts
> +      explorers: ['https://explorerl2-fluffy-bob-7mjgi9pmtg.t.conduit.xyz/'],
```suggestion
      explorers: ['https://testnet-explorer.gobob.xyz/'],
```

2023-12-19 02:30 UTC, nud3l approved these changes

2023-12-19 02:30 UTC, merged